### ISSUE TITLE
Alphabetical ordering on publisher page

### ISSUE THREAD

**Issue by dalepotter** [okfn/ckanext-iati#79]
Looking at the [Registry publisher page](https://www.iatiregistry.org/publisher), it seems that the ordering of publishers has reverted to alphabetical by publisher ID (rather than actual name, which is more user-friendly).  We have also noticed that functionality to sort by the 'Publisher' column has disappeared.

![image](https://cloud.githubusercontent.com/assets/8247168/17140623/054b6bae-5341-11e6-9b4a-12cfe4355da0.png)

This was a bespoke change that we asked OKF for a while ago and it seems that the recent upgrade may have removed this?  Could we look into this to get it fixed?

Curiously, the list appears to order correctly on the staging site, and with the ability to sort by the 'Publisher' column: https://iati-staging.ckan.io/publisher

![image](https://cloud.githubusercontent.com/assets/8247168/17140608/ee50b7c4-5340-11e6-9270-68da19a8d87a.png)

**Comment by peppe1337** [comment]
Hey Dale,

thanks for rasing this. We will take care about this.

Best regards,

Chris

**Comment by dalepotter** [comment]
Hi @peppe1337 just wondered if there was an update on this one as [the issue still appears to remain](https://www.iatiregistry.org/publisher) on the live site.

**Comment by peppe1337** [comment]
Hey @dalepotter - I received an update from my development team on Friday. The ascending bug, was one of the older ones and which was gathered on GitHub.

During our migration plans we agreed that this bug will be fixed on the new portal version, what we did and it is working. I asked my devs, if we can't take the new solution and push it on the older portal. They tried it and said it failed due to the older version of CKAN. 

If you want to, I can raise this again, but the older version of CKAN allows sorting only by name (URL) and package_count.  We would need to develop and this would take some time.

To be honest, I would leave it like it is for the moment, because you have a running solution on your new CKAN version.

**Comment by markbrough** [comment]
@peppe1337 I'm pretty sure this issue is a result of #74 ([detailed here](http://discuss.iatistandard.org/t/iati-registry-now-using-https/511/10)). There is a `tablesorter` plugin which should be re-sorting correctly in the browser, but it is not working because the script is halted due to the warnings.

**Comment by peppe1337** [comment]
@markbrough thanks for your help. I will forward this to the devs.

**Comment by dalepotter** [comment]
@peppe1337 any update?

**Comment by peppe1337** [comment]
@dalepotter I wrote you an email.

**Comment by dalepotter** [comment]
Just to update here following conversations by email. We understand from @peppe1337 that no functionality for alphabetical ordering was available in the old CKAN version (i.e. the [soon-to-be upgraded version](http://www.aidtransparency.net/news/important-changes-to-the-iati-registry-api) of the IATI Registry), and we have not found any concrete evidence that such functionality worked in the current version of the Registry.

CKAN support have not been bale to confirm that this definitely relates to the SSL issues, as the source has been difficult to track it down. After almost a day of investigations by CKAN, it seems that the unprotected source is coming from a callback function which is from CKAN itself.

Given that we understand that both should be resolved when we upgrade to the new CKAN version in October, both this and remaining issues from #74 ([detailed here](http://discuss.iatistandard.org/t/iati-registry-now-using-https/511/10)) are being marked as a #wontfix for now.
